# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 79c4c8c40011844ecebce977926afcf4ac84a3562b07ea151069166e74d5a9027c62f2d75917db0b5152b05bfabbfe2f302938c9c318d6adad54453fe019e8c0

test:
  domain_name: example.com 
  secret_key_base: 21104c1861f2b7b7a760199e99ccc6e5d9b5c30073bce75188aed92a854e5f0f80b227b1f39f104dcb331c3bb2338d272fa8c5e7c4a6209e3e7b8d43fbdd4384

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
